baseURL = "https://beginnerCPPis.github.io/OCEANS/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "m10c"
publishDir = "docs"
canonifyurls = true



[params]
author = "maki"
description = "simple introduction something like hobby"
[params.style]

 # darkColor = "#2a3738"                                                                                                                                                                                                                     \
                                                                                                                                                                                                                                              
 # darkestColor = "#d35050"                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                              
   darkColor = "#212121"
 # lightColor = "#f5e3e0"                                                                                                                                                                                                                    \
                                                                                                                                                                                                                                              
 # lightestColor = "#f5f5f5"                                                                                                                                                                                                                 \
                                                                                                                                                                                                                                              
 # primaryColor = "#fff"                                                                                                                                                                                                                      


